/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/f1auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** F1Auth Status */
        get: operations["f1auth_status_api_f1auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/f1auth/refresh/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** F1Auth Refresh Start */
        post: operations["f1auth_refresh_start_api_f1auth_refresh_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/idle-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Idle Data
         * @description Fetches standings and news for the idle dashboard.
         */
        get: operations["get_idle_data_api_idle_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Milestones
         * @description Stats to be beaten for the upcoming race. Simplified prototype.
         */
        get: operations["get_milestones_api_milestones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/driver/{driver_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Driver Stats
         * @description Fetches career statistics for a specific driver.
         */
        get: operations["get_driver_stats_api_driver__driver_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/constructor/{constructor_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Constructor Stats
         * @description Fetches career statistics for a specific constructor.
         */
        get: operations["get_constructor_stats_api_constructor__constructor_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/circuit/{circuit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Circuit Details
         * @description Detailed circuit info plus historical data for the given season.
         *     season=2026 fetches 2025 results (season-1); returns available_years.
         */
        get: operations["get_circuit_details_api_circuit__circuit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/race-weekend/{circuit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Race Weekend
         * @description Results for one session of a race weekend: race | quali | sprint | fp1 | fp2 | fp3.
         *     FP sessions are only available for year >= 2023 via OpenF1.
         */
        get: operations["get_race_weekend_api_race_weekend__circuit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CircuitDetailsResponse */
        CircuitDetailsResponse: {
            /** Circuit */
            circuit: components["schemas"]["CircuitRecord"] | {
                [key: string]: unknown;
            };
            /** Prev Results */
            prev_results: {
                [key: string]: unknown;
            }[];
            /** Available Years */
            available_years: number[];
            stats: components["schemas"]["CircuitStats"];
            /** Upgrades */
            upgrades: components["schemas"]["UpgradeRecord"][];
        };
        /** CircuitRecord */
        CircuitRecord: {
            /** Circuitid */
            circuitId: string;
            /** Circuitname */
            circuitName: string;
            Location: components["schemas"]["LocationRecord"];
        } & {
            [key: string]: unknown;
        };
        /** CircuitStats */
        CircuitStats: {
            /** Corners */
            corners: number;
            /** Elevation Gain */
            elevation_gain: number;
            /** Laps */
            laps: number;
            /** Lap Record */
            lap_record: string;
        };
        /** ConstructorRecord */
        ConstructorRecord: {
            /** Constructorid */
            constructorId: string;
            /** Name */
            name: string;
            /** Nationality */
            nationality: string;
        } & {
            [key: string]: unknown;
        };
        /** ConstructorStanding */
        ConstructorStanding: {
            /** Position */
            position: string;
            /** Points */
            points: string;
            Constructor: components["schemas"]["ConstructorRecord"];
        } & {
            [key: string]: unknown;
        };
        /** ConstructorStatsResponse */
        ConstructorStatsResponse: {
            info: components["schemas"]["ConstructorRecord"];
            /** Wins */
            wins: string;
            /** Championships */
            championships: number;
        };
        /** DriverRecord */
        DriverRecord: {
            /** Driverid */
            driverId: string;
            /** Givenname */
            givenName: string;
            /** Familyname */
            familyName: string;
            /** Nationality */
            nationality: string;
        } & {
            [key: string]: unknown;
        };
        /** DriverStanding */
        DriverStanding: {
            /** Position */
            position: string;
            /** Points */
            points: string;
            Driver: components["schemas"]["DriverRecord"];
            /** Constructors */
            Constructors: components["schemas"]["ConstructorRecord"][];
        } & {
            [key: string]: unknown;
        };
        /** DriverStatsResponse */
        DriverStatsResponse: {
            info: components["schemas"]["DriverRecord"];
            /** Wins */
            wins: string;
            /** Championships */
            championships: number;
            /** Career Teams */
            career_teams: components["schemas"]["ConstructorRecord"][];
        };
        /** F1AuthStatusResponse */
        F1AuthStatusResponse: {
            /** Valid Until */
            valid_until: number | null;
            /** Needs Refresh */
            needs_refresh: boolean;
        };
        /** FPResult */
        FPResult: {
            /** Position */
            position: string;
            /** Driver Number */
            driver_number: number;
            /** Family Name */
            family_name: string | null;
            /** Given Name */
            given_name: string | null;
            /** Team Name */
            team_name: string | null;
            /** Time */
            time: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdleDataResponse */
        IdleDataResponse: {
            /** Driver Standings */
            driver_standings: components["schemas"]["DriverStanding"][];
            /** Constructor Standings */
            constructor_standings: components["schemas"]["ConstructorStanding"][];
            /** News */
            news: components["schemas"]["NewsArticle"][];
            /** Schedule */
            schedule: components["schemas"]["ScheduledRace"][];
            /** Next Race */
            next_race: components["schemas"]["RaceSummary"] | {
                [key: string]: unknown;
            };
        };
        /** LocationRecord */
        LocationRecord: {
            /** Locality */
            locality: string;
            /** Country */
            country: string;
        } & {
            [key: string]: unknown;
        };
        /** MilestoneErrorResponse */
        MilestoneErrorResponse: {
            /** Error */
            error: string;
        };
        /** MilestoneRecord */
        MilestoneRecord: {
            /** Stat */
            stat: string;
            /** Value */
            value: string;
            /** Target */
            target: string;
        } & {
            [key: string]: unknown;
        };
        /** MilestonesResponse */
        MilestonesResponse: {
            /** Circuit Name */
            circuit_name: string | null;
            /** Milestones */
            milestones: components["schemas"]["MilestoneRecord"][];
        };
        /** NewsArticle */
        NewsArticle: {
            /** Headline */
            headline: string;
            /** Description */
            description: string;
            /**
             * Images
             * @default []
             */
            images: components["schemas"]["NewsImage"][];
            links: components["schemas"]["NewsLinks"];
        } & {
            [key: string]: unknown;
        };
        /** NewsImage */
        NewsImage: {
            /** Url */
            url: string;
        } & {
            [key: string]: unknown;
        };
        /** NewsLinks */
        NewsLinks: {
            web: components["schemas"]["NewsWebLink"];
        } & {
            [key: string]: unknown;
        };
        /** NewsWebLink */
        NewsWebLink: {
            /** Href */
            href: string;
        } & {
            [key: string]: unknown;
        };
        /** QualiResult */
        QualiResult: {
            /** Position */
            position: string | null;
            /** Driver Id */
            driver_id: string | null;
            /** Family Name */
            family_name: string | null;
            /** Given Name */
            given_name: string | null;
            /** Team */
            team: string | null;
            /** Time */
            time: string;
            /** Q1 */
            q1: string | null;
            /** Q2 */
            q2: string | null;
            /** Q3 */
            q3: string | null;
        };
        /** RaceResult */
        RaceResult: {
            /** Position */
            position: string | null;
            /** Driver Id */
            driver_id: string | null;
            /** Family Name */
            family_name: string | null;
            /** Given Name */
            given_name: string | null;
            /** Team */
            team: string | null;
            /** Status */
            status: string | null;
            /** Is Finished */
            is_finished: boolean;
            /** Time */
            time: string | null;
        };
        /** RaceSummary */
        RaceSummary: {
            /** Round */
            round: string;
            /** Racename */
            raceName: string;
            /** Date */
            date: string;
            Circuit: components["schemas"]["CircuitRecord"];
        } & {
            [key: string]: unknown;
        };
        /** RaceWeekendResponse */
        RaceWeekendResponse: {
            /** Results */
            results: (components["schemas"]["RaceResult"] | components["schemas"]["SprintResult"] | components["schemas"]["QualiResult"] | components["schemas"]["FPResult"])[];
            /** Available */
            available: boolean;
        };
        /** RefreshStartResponse */
        RefreshStartResponse: {
            /** Url */
            url: string;
        };
        /** ScheduledRace */
        ScheduledRace: {
            /** Round */
            round: string;
            /** Racename */
            raceName: string;
            /** Date */
            date: string;
            Circuit: components["schemas"]["CircuitRecord"];
        } & {
            [key: string]: unknown;
        };
        /** SprintResult */
        SprintResult: {
            /** Position */
            position: string | null;
            /** Driver Id */
            driver_id: string | null;
            /** Family Name */
            family_name: string | null;
            /** Given Name */
            given_name: string | null;
            /** Team */
            team: string | null;
            /** Is Finished */
            is_finished: boolean;
            /** Time */
            time: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Is Live */
            is_live: boolean;
        };
        /** UpgradeRecord */
        UpgradeRecord: {
            /** Team */
            team: string;
            /** Item */
            item: string;
            /** Impact */
            impact: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    f1auth_status_api_f1auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["F1AuthStatusResponse"];
                };
            };
        };
    };
    f1auth_refresh_start_api_f1auth_refresh_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStartResponse"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_idle_data_api_idle_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdleDataResponse"];
                };
            };
        };
    };
    get_milestones_api_milestones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestonesResponse"] | components["schemas"]["MilestoneErrorResponse"];
                };
            };
        };
    };
    get_driver_stats_api_driver__driver_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_constructor_stats_api_constructor__constructor_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                constructor_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConstructorStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_circuit_details_api_circuit__circuit_id__get: {
        parameters: {
            query?: {
                season?: number;
            };
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CircuitDetailsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_race_weekend_api_race_weekend__circuit_id__get: {
        parameters: {
            query?: {
                year?: number;
                session?: string;
            };
            header?: never;
            path: {
                circuit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceWeekendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
